// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TTBack.Models;

#nullable disable

namespace TTBack.Migrations
{
    [DbContext(typeof(TrekTogetherContext))]
    partial class TrekTogetherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TTBack.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarModel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("carModel");

                    b.Property<string>("CarYear")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("carYear")
                        .IsFixedLength();

                    b.Property<string>("GosNomer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("carMake");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Car", (string)null);
                });

            modelBuilder.Entity("TTBack.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TTBack.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("arrivalCity");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("availableSeats");

                    b.Property<int?>("CarId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureCity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("departureCity");

                    b.Property<DateTime?>("DepartureData")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("departureData");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driverId");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("TTBack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDriver")
                        .HasColumnType("boolean")
                        .HasColumnName("isDriver");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phoneNumber");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TTBack.Models.UserTrip", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("UserTrips");
                });

            modelBuilder.Entity("TTBack.Models.Car", b =>
                {
                    b.HasOne("TTBack.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Car_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TTBack.Models.Trip", b =>
                {
                    b.HasOne("TTBack.Models.Car", "Car")
                        .WithMany("Trips")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK_Trip_Car");

                    b.HasOne("TTBack.Models.User", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .HasConstraintName("FK_Trip_User");

                    b.Navigation("Car");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TTBack.Models.UserTrip", b =>
                {
                    b.HasOne("TTBack.Models.Trip", "Trip")
                        .WithMany("UserTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTBack.Models.User", "User")
                        .WithMany("UserTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TTBack.Models.Car", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TTBack.Models.Trip", b =>
                {
                    b.Navigation("UserTrips");
                });

            modelBuilder.Entity("TTBack.Models.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Trips");

                    b.Navigation("UserTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
